config/routes.rb
PomodoroTimer::Application.routes.draw do
  root to: "home#index"
  resources :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :content
  validates_inclusion_of :done, in: [true, false]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    render json: Task.all
  end

  def create
    render json: Task.create!(task_params)
  end

  def update
    task = Task.find(params[:id])
    render json: task.update_attributes!(task_params)
  end

  def destroy
    Task.find(params[:id]).destroy
    render nothing: true
  end

  private

  def task_params
    params[:task].permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/about.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <article class="about-text">
        <h2> About Pomodoro </h2>

        <p> The Pomodoro Technique helps you focus on one thing only and avoid distraction.
          Select a task, set up a timer for 25 minutes and start working. </p>

        <p> If anything disturbs you - your Pomodoro is over and you have to start again.
          There is no such thing like pause. </p>

        <div class="image-in-text">
          <img src="http://pomodorotechnique.com/wp-content/themes/pomodoro/img/getstarted/why_1.png" alt="pomodoro hearth">
        </div>

        <p>Why do I have to finish the whole pomodoro? </p>

        <p>We are most productive right when we do not try to multitask, check facebook statuses or think on
          thousands
          of
          other stuff.
          Finishing a pomodoro without interrupts will teach you to master your concetration.</p>

        <p>You will pretty soon see how 25 minutes is enough time to do almost anything.</p>

        <p>Fore more reference about this technique check the official page <a href="http://pomodorotechnique.com/">
          here</a>.</p>
      </article>
    </div>

    <div class="col-md-6 col-md-offset-3">
      <article class="about-text">
        <h2 class="h2-in-text"> About this app</h2>

        <p>This app is free to use for everyone.
          It does not require an account to use the Pomodoro timer or tasks, however to keep track of your
          progress
          you can create one.</p>

        <p>If you are working anonymously and you will close the browser, you will lose our your tasks.</p>

        <p>Creating an account is very simple, all you need to do is give us your email and choose a pasword. We
          promise
          not to send you anything. </p>

        <p> You can register and start to use Pomodoro Timer with its full features right <a href="">here</a>.</p>
      </article>
    </div>
    <div class="col-md-6 col-md-offset-3">
      <article class="about-text last">
        <h2> About us</h2>

        <p>This is a school project made by Zuzana Dostalova. Zuzana committed herself to learn Ruby on Rails and
          this
          app will hopefully help her to master that language.</p>

        <div class="image-in-text">
          <img src="http://upload.wikimedia.org/wikipedia/en/thumb/e/e9/Ruby_on_Rails.svg/150px-Ruby_on_Rails.svg.png" alt="ruby on rails image">
        </div>
        <p>You can check her other project (an awesome app about self-improvement, where you need to think and
          write) <a href="http://journeyapp.net">here</a>.
        </p>

      </article>
    </div>
  </div>
</section>

app/views/home/home.html.erb
<section class="container">
  <div class="row index-row">
    <div class="col-md-5">
      <aside class="image-box">
        <img src="http://pomodorotechnique.com/wp-content/themes/pomodoro/img/logos/logo.png" alt="pomodoro image">
      </aside>
    </div>

    <div class="col-md-5 col-md-offset-1">
      <article class="text">
        <p> The Pomodoro Technique is very simple yet powerful tool for being productive. Just work for 25 minutes,
          focus on <strong> one task only </strong> and then take a break!</p>

        <p> Click on start to <strong> begin your pomodoro</strong>, go on tasks to manage your work or learn more
          about this app, pomodoro technique and us. </p>

        <div class="login">
          <%= link_to new_user_registration_path do %>
            <span class="button main"> Sign-up </span>
          <% end %>
          <%= link_to new_user_session_path do %>
            <span class="login_text">login or</span>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<h1>ember!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Pomodoro Timer</title>

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="ember-app">
  </div>

  <!-- google analytics -->
</body>
</html>

app/views/tasks/_task.html.erb
<li class="task">
  <span class="task-text">
    <% if task.done %>
      <strike><%= task.content %></strike>
    <% else %>
      <%= task.content %>
    <% end %>
  </span>
  <%= link_to "done", task_path(task, done: !task.done), method: :put, class: "option done_action", remote: true %>
  <%= link_to "delete", task, method: :delete, class: "option delete_action", data: { confirm: "Are you sure?" }, remote: true %>
</li>

app/views/tasks/create.js.erb
add("<%= j @task.to_json %>)";
renderTasks(0;)

app/views/tasks/destroy.js.erb
$(".tasks").html("<%= j render @tasks %>");

app/views/tasks/index.html.erb
<section class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <aside class="image-in-text">
        <img src="http://www.ekolamp.cz/wp-content/uploads/2011/09/underConstruction.gif" width="300px" alt="under construction">
      </aside>
    </div>
  </div>
</section>

app/views/tasks/start.html.erb
<section class="timer">
  <div class="buttons">
    <div class="twenty-five">25</div>
    <div class="five">5</div>
  </div>
</section>
<section class="container">
  <div class="row start-row">

    <div class="headline">
      <div class="main twenty clickable"><p>20</p></div>
      <div class="main pink five clickable"><p>5</p></div>
      <div class="timer">
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <span class="dot">.</span>
        <p class="hidden"> Interrupt?</p>
      </div>

      <div class="overlay"></div>
    </div>
    <div id="box">
      <%= form_for Task.new, remote: true do |f| %>
        <%= f.text_field :content, placeholder: "Type a task and hit enter" %>
      <% end %>

    </div>
    <div class="quote" id="quote">

    </div>
  </div>

  <div class="col-md-8">
    <ul class="tasks">
      <%= render @tasks %>
    </ul>
  </div>

  <div class="col-md-3 col-md-offset-1">
    <aside class="hint">
      <h3>Instructions:</h3>

      <p>Select a task which you are going to work on from a list. You can add new tasks any time. </p>

      <p>When you have one task selected, you can start a pomodoro by clicking on a 25 button.</p>

      <p>Don't forget you can't pause it! After work, use a 5 minutes button to take a break.
      </p>
    </aside>
  </div>
</div>
</section>

app/views/tasks/update.js.erb
$(".tasks").html("<%= j render @tasks %>");